# Generated by Django 4.2.4 on 2023-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LijstwerkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='lijstwerk/')),
            ],
        ),
        migrations.CreateModel(
            name='MuurschilderingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='muurschildering/')),
            ],
        ),
        migrations.CreateModel(
            name='SausProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='sauzen/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SierpleisterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='sierpleister/')),
            ],
        ),
        migrations.CreateModel(
            name='StucProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='stucwerk/')),
            ],
        ),
        migrations.CreateModel(
            name='Offerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('woonplaats', models.CharField(max_length=100)),
                ('telefoon_nummer', models.CharField(max_length=15)),
                ('uw_aanvraag', models.TextField()),
                ('services', models.ManyToManyField(blank=True, to='core.service')),
            ],
        ),
    ]
